name: CI

on:
  pull_request:
    branches: [dev, master]
    # push: [dev, master]

jobs:

  build:
    runs-on: ubuntu-20.04 # ubuntu-latest, windows-2022, macos-11

    # env: 
      # SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      # SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}	

    steps:
      # Install Dependencies

      # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      # @seemore: https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Setup Composer
      # - name: Use composer
      #   uses: php-actions/composer@v6
      #   with:
      #     php_version: '8.1'
      #     version: 2
          # php_extensions: imagick

      # - name: Cache Composer dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      # - name: Check format by Prettier #Worked?
      #   run: npx run prettier "**/*.{php,yml,html,css}" --check
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check **/*.{php,css}

      # Commit Message Test
      # Unit Test
      # - run: npm test -- --coverage
      #   env:
      #     CI: true
      # Upload Code coverage
      # Build on Merge
      # Upload Build as Artifact on Merge
      # Deploy to Staging Server on dev branch Merge
      # Deploy to Production Server on dev master Merge
      # Upload Coverage to Codecov on dev master Merge
      # Cache Dependencies